/* GENERATED by make_estimator_images.py -- do not edit by hand.
 *
 * Real dimensions of every estimator derivative, so each <img> can carry
 * exact width/height (no layout shift) and an honest srcset.
 */
export const ESTIMATOR_IMAGES = {
  "hero-great-trenching:thumb": {
    "stem": "hero-great-trenching",
    "shape": "thumb",
    "variants": [
      {
        "width": 104,
        "height": 104
      },
      {
        "width": 208,
        "height": 208
      }
    ]
  },
  "hero-narrow-trench:card": {
    "stem": "hero-narrow-trench",
    "shape": "card",
    "variants": [
      {
        "width": 240,
        "height": 240
      },
      {
        "width": 460,
        "height": 460
      }
    ]
  },
  "hero-narrow-trench:thumb": {
    "stem": "hero-narrow-trench",
    "shape": "thumb",
    "variants": [
      {
        "width": 104,
        "height": 104
      },
      {
        "width": 208,
        "height": 208
      }
    ]
  },
  "hero-narrow-trench:wide": {
    "stem": "hero-narrow-trench",
    "shape": "wide",
    "variants": [
      {
        "width": 400,
        "height": 267
      },
      {
        "width": 760,
        "height": 507
      }
    ]
  },
  "ndd-exposed-pipe:thumb": {
    "stem": "ndd-exposed-pipe",
    "shape": "thumb",
    "variants": [
      {
        "width": 104,
        "height": 104
      },
      {
        "width": 208,
        "height": 208
      }
    ]
  },
  "ndd-services-and-roots:card": {
    "stem": "ndd-services-and-roots",
    "shape": "card",
    "variants": [
      {
        "width": 240,
        "height": 240
      },
      {
        "width": 460,
        "height": 460
      }
    ]
  },
  "ndd-services-and-roots:thumb": {
    "stem": "ndd-services-and-roots",
    "shape": "thumb",
    "variants": [
      {
        "width": 104,
        "height": 104
      },
      {
        "width": 208,
        "height": 208
      }
    ]
  },
  "ndd-services-and-roots:wide": {
    "stem": "ndd-services-and-roots",
    "shape": "wide",
    "variants": [
      {
        "width": 400,
        "height": 267
      },
      {
        "width": 640,
        "height": 427
      }
    ]
  },
  "ndd-tight-access:context": {
    "stem": "ndd-tight-access",
    "shape": "context",
    "variants": [
      {
        "width": 380,
        "height": 285
      },
      {
        "width": 640,
        "height": 480
      }
    ]
  },
  "ndd-tight-access:thumb": {
    "stem": "ndd-tight-access",
    "shape": "thumb",
    "variants": [
      {
        "width": 104,
        "height": 104
      },
      {
        "width": 208,
        "height": 208
      }
    ]
  },
  "port-03:context": {
    "stem": "port-03",
    "shape": "context",
    "variants": [
      {
        "width": 380,
        "height": 285
      },
      {
        "width": 740,
        "height": 555
      }
    ]
  },
  "port-03:thumb": {
    "stem": "port-03",
    "shape": "thumb",
    "variants": [
      {
        "width": 104,
        "height": 104
      },
      {
        "width": 208,
        "height": 208
      }
    ]
  },
  "rig-access:context": {
    "stem": "rig-access",
    "shape": "context",
    "variants": [
      {
        "width": 380,
        "height": 285
      },
      {
        "width": 740,
        "height": 555
      }
    ]
  },
  "rig-access:thumb": {
    "stem": "rig-access",
    "shape": "thumb",
    "variants": [
      {
        "width": 104,
        "height": 104
      },
      {
        "width": 208,
        "height": 208
      }
    ]
  },
  "service-access:thumb": {
    "stem": "service-access",
    "shape": "thumb",
    "variants": [
      {
        "width": 104,
        "height": 104
      },
      {
        "width": 208,
        "height": 208
      }
    ]
  },
  "service-leak:thumb": {
    "stem": "service-leak",
    "shape": "thumb",
    "variants": [
      {
        "width": 104,
        "height": 104
      },
      {
        "width": 208,
        "height": 208
      }
    ]
  },
  "service-potholing-card:card": {
    "stem": "service-potholing-card",
    "shape": "card",
    "variants": [
      {
        "width": 240,
        "height": 240
      },
      {
        "width": 400,
        "height": 400
      }
    ]
  },
  "service-potholing-card:thumb": {
    "stem": "service-potholing-card",
    "shape": "thumb",
    "variants": [
      {
        "width": 104,
        "height": 104
      },
      {
        "width": 208,
        "height": 208
      }
    ]
  },
  "service-potholing-card:wide": {
    "stem": "service-potholing-card",
    "shape": "wide",
    "variants": [
      {
        "width": 400,
        "height": 267
      }
    ]
  },
  "tight-access:thumb": {
    "stem": "tight-access",
    "shape": "thumb",
    "variants": [
      {
        "width": 104,
        "height": 104
      },
      {
        "width": 208,
        "height": 208
      }
    ]
  }
};
